version: '3.8'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    volumes:
      - /mnt/HomeLab/pihole_config:/etc/pihole
      - /mnt/HomeLab/pihole_dnsmasq:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8089:80"
      - "443:443"
    environment:
      TZ: 'America/Chicago'
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 8.8.4.4

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /mnt/HomeLab/homeassistant_config:/config
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - pihole
    restart: unless-stopped
    ports:
      - "8123:8123"
    dns:
      - 1.1.1.1
      - 8.8.4.4

  ollama:
      image: drrohin/home_lab-stack-ollama:latest
      container_name: ollama
#      volumes:
#        - ollama:/root/.ollama
      ports:
        - "11434:11434"
      restart: unless-stopped

  ollama-webui:
    image: drrohin/home_lab-stack-ollama-webui:latest
    container_name: ollama-webui
    volumes:
      - /mnt/HomeLab/ollama-webui:/app/backend/data
      - /mnt/HomeLab/ollama-webui-config:/app/backend/config
      - /mnt/HomeLab/ollama-webui-logs:/app/backend/logs
      - /mnt/HomeLab/ollama-webui-models:/app/backend/models
    depends_on:
      - pihole
      - homeassistant
      - ollama
    ports:
      - "3000:8080"
    environment:
      - "OLLAMA_API_BASE_URL=http://ollama:11434/api"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

#  mongodb:
#    container_name: mongodb
#    image: mongo:latest
#    volumes:
#      - type: volume
#        source: mongodb_data
#        target: /data/db
#    ports:
#      - "27017:27017"
#    restart: unless-stopped

volumes:
  ollama: {}
#  ollama-data: {}
#  ollama-webui: {}
#  ollama-webui-config: {}
#  ollama-webui-logs: {}
#  ollama-webui-models: {}
#  homeassistant: {}
#  homeassistant_config: {}
#  pihole_config: {}
#  pihole_dnsmasq: {}
#  mongodb_data: {}

networks:
  default:
    external:
      name: home_lab
