version: '3.8'

services:
  pihole:
    build:
      context: .
      dockerfile: Dockerfile-pihole
    

  homeassistant:
    build:
      context: .
      dockerfile: Dockerfile-homeassistant
    

  anythingllm:
    build:
      context: .
      dockerfile: Dockerfile-anythingllm
    

  ollama:
    build:
      context: .
      dockerfile: Dockerfile-ollama
    
